# Generated by Django 3.2.9 on 2022-11-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_de_la_empresa', models.CharField(max_length=250, verbose_name='Empresa')),
                ('numero_de_ruc', models.CharField(max_length=250, verbose_name='RUC')),
                ('nombre_del_nexo', models.CharField(max_length=250, verbose_name='Nexo')),
                ('telefono_del_nexo', models.CharField(max_length=250, verbose_name='Tel. Nexo')),
                ('mail_del_nexo', models.CharField(max_length=250, verbose_name='Mail Nexo')),
                ('nombre_contacto_pagos', models.CharField(max_length=250, verbose_name='Contacto de pago')),
                ('telefono_contacto_pagos', models.CharField(max_length=250, verbose_name='Tel. Conacto Pago')),
                ('mail_contacto_pagos', models.CharField(max_length=250, verbose_name='Mail Conacto Pago')),
                ('fecha_de_vinculacion', models.DateField(verbose_name='Fecha de Vinculacion')),
                ('notas_adicionales', models.CharField(max_length=250, verbose_name='Notas')),
                ('forma_de_pago_habitual', models.CharField(max_length=20, verbose_name='Pago Habitual')),
                ('banco', models.CharField(max_length=250, verbose_name='Banco')),
                ('titular_de_la_cuenta', models.CharField(max_length=250, verbose_name='Titular de la cuenta')),
                ('tipo_de_cuenta', models.CharField(max_length=250, verbose_name='Tipo de Cuenta')),
                ('numero_de_cuenta', models.CharField(max_length=250, verbose_name='Nro de Cuenta')),
                ('documento_de_cuenta', models.CharField(max_length=250, verbose_name='Documento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de departamento')),
                ('jerarquia', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='Jerarquia asignada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='miembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombres', models.CharField(max_length=250, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('nacionalidad', models.CharField(max_length=250, verbose_name='Nacionalidad')),
                ('numero_de_documento', models.CharField(max_length=250, verbose_name='CIN')),
                ('fecha_de_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono_particular', models.CharField(max_length=250, verbose_name='Tel. Part.')),
                ('telefono_corporativo', models.CharField(max_length=250, verbose_name='Tel. Corp.')),
                ('mail_particular', models.CharField(max_length=250, verbose_name='Mail Part.')),
                ('mail_corporativo', models.CharField(max_length=250, verbose_name='Mail Corp.')),
                ('fecha_de_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_de_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('motivo_de_salida', models.CharField(max_length=250, verbose_name='Motivo de Salida')),
                ('cargo', models.CharField(max_length=250, verbose_name='Cargo')),
                ('notas_adicionales', models.CharField(max_length=250, verbose_name='Notas')),
                ('contribuyente_set', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, verbose_name='SET')),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], max_length=25, verbose_name='Estado Civil')),
                ('hijos', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=25, verbose_name='Hijos')),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('PNM', 'Prefiero no mencionarlo')], max_length=25, verbose_name='Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('hora_entrega', models.TimeField(verbose_name='Hora de Entrega')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.miembro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rubro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('empleado_o_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.cliente')),
                ('nombre_de_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('forma_de_pago', models.CharField(max_length=200, verbose_name='Forma de Pago')),
                ('tipo_de_cobro', models.CharField(max_length=200, verbose_name='Tipo de cobro')),
                ('nombre_de_pago', models.CharField(max_length=200, verbose_name='Nombre de Pago')),
                ('monto_de_pago', models.IntegerField(verbose_name='Monto de Pago')),
                ('numero_de_factura', models.CharField(max_length=200, verbose_name='Factura Nro')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.rubro')),
                ('titular_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.cliente')),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='egreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('forma_de_pago', models.CharField(max_length=200, verbose_name='Forma de Pago')),
                ('tipo_de_pago', models.CharField(max_length=200, verbose_name='Tipo de Pago')),
                ('nombre_de_pago', models.CharField(max_length=200, verbose_name='Nombre de Pago')),
                ('monto_de_pago', models.IntegerField(verbose_name='Monto de Pago')),
                ('numero_de_factura', models.CharField(max_length=200, verbose_name='Factura Nro')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.rubro')),
                ('titular_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
