# Generated by Django 3.1.4 on 2021-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('staff_no', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.TextField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
                ('designation', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=20)),
                ('reporting_officer', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('joining_date', models.DateField(verbose_name='date of joining (yyyy-mm-dd)')),
                ('qualification', models.CharField(max_length=20)),
                ('specialisation', models.TextField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('internal_phone_no', models.CharField(blank=True, max_length=30, null=True)),
                ('tech_skills', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
