# Generated by Django 3.1.4 on 2021-02-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='internal_phone_no',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='specialisation',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='tech_skills',
        ),
    ]
