# Generated by Django 3.2.9 on 2022-11-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
